<form action="<?php echo Mage::getUrl('students/index/nstudent') ?>" method="post">
    <fieldset>
        <div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
        <ul>
            <li>
                <label for="first_name">First Name</label>
                <input type="text" id="first_name" name="first_name" />
            </li>
            <li>
                <label for="last_name">Last Name</label>
                <input type="text" id="last_name" name="last_name" />
            </li>
            <li>
                <label for="email">Email</label>
                <input type="text" id="email" name="email" />
            </li>
            <li><input type="submit" value="Save" /></li>
        </ul>
    </fieldset>
</form>